name: Terraform
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'
  push:
    branches:
    - main
  pull_request:
env:
  VCS_WORKSPACE_NAME: github-workflow
  TF_VERSION: 0.14.3
  WORKING_DIRECTORY: ''
  VCS_REPO: mayankagarwal19911/test-workflow
  VCS_BRANCH: main
  TFE_ADDR: https://app.terraform.io
  TFE_ORG: test-cicd
  namespace: Test1
permissions:
  contents: read
jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    environment: development
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: docker build
      run: |
        echo "Hello github.event.inputs.name.default"
        echo "- in github.event.inputs.home.default"
      
      
    
